version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .backend.env
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '0.0.0.0:5556:80'
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15
    env_file:
      - .db.env
    volumes:
      - postgres_data:/var/lib/postgresql-15/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - '5555:5555'
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
