services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - WITH_PUSH=${WITH_PUSH:-false}
      - WITH_SEED=${WITH_SEED:-false}
      - WITH_MIGRATION=${WITH_MIGRATION:-false}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: ['./entrypoint.sh', 'npm', 'run', 'start']
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://backend:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - VITE_HOST_URL=${VITE_HOST_URL}
    ports:
      - '5556:80'
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql-15/data
      - ./db-backup/backups:/backups
    ports:
      - '5555:5555'
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  db-backup:
    build:
      context: .
      dockerfile: ./db-backup/Dockerfile
    env_file:
      - .env
    volumes:
      - ./db-backup/backups:/backups
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
