INSERT INTO "Product" ("code", "name") VALUES
('ST', 'СТ'),
('STA', 'СТА'),
('STA_45', 'СТА 45'),
('ST_ECONOMY', 'СТ Эконом'),
('ST_LITE', 'СТ Лайт'),
('ST_45', 'СТ 45'),
('ST_CALICO', 'СТ Бязь'),
('BT', 'БТ'),
('BTA', 'БТА'),
('BTA_45', 'БТА 45'),
('BT_LITE', 'БТ Лайт'),
('BT_ECONOMY', 'БТ Эконом'),
('BT_45', 'БТ 45'),
('EVA', 'ЭВА'),
('EVA_LP', 'Эва ЛП'),
('EVA_ECONOMY', 'ЭВА Эконом'),
('EVA_ECONOMY_45', 'ЭВА Эконом 45'),
('MAHRA_150', 'Махра 150'),
('MAHRA', 'Махра'),
('MAHRA_LP', 'Махра ЛП'),
('MAHRA_A', 'Махра А'),
('MAHRA_ECONOMY', 'Махра Эконом'),
('MAHRA_45', 'Махра 45'),
('MAHRA_ECONOMY_45', 'Махра Эконом 45'),
('MEDIUM', 'Медиум'),
('MEDIUM_45', 'Медиум 45'),
('MEDIUM_LP', 'Медиум ЛП'),
('MEDIUM_LP_45', 'Медиум ЛП 45'),
('CLASSIC', 'Классик'),
('CLASSIC_45', 'Классик 45'),
('CLASSIC_LP', 'Классик ЛП'),
('CLASSIC_LP_45', 'Классик ЛП 45'),
('CLASSIC_PLUS', 'Классик Плюс'),
('CLASSIC_PLUS_45', 'Классик Плюс 45'),
('CLASSIC_PLUS_LP', 'Классик Плюс ЛП'),
('CLASSIC_PLUS_LP_45', 'Классик Плюс ЛП 45'),
('BUISNESS', 'Бизнес'),
('BUISNESS_45', 'Бизнес 45'),
('BUISNESS_LP', 'Бизнес ЛП'),
('BUISNESS_LP_45', 'Бизнес ЛП 45'),
('VIETNAM_D3', 'Вьетнамки D3'),
('VIETNAM_D4', 'Вьетнамки D4'),
('OPTIMA', 'Оптима'),
('OPTIMA_45', 'Оптима 45'),
('OPTIMA_A', 'Оптима А'),
('OPTIMA_A_45', 'Оптима А 45');

INSERT INTO "Worker" ("id", "name") VALUES
(416, 'Зариф'),
(470, 'Бегзод'),
(145, 'Бобур'),
(469, 'Гайрат'),
(295, ''),
(501, '');