import { Injectable } from '@nestjs/common';

@Injectable()
export class ProductService {
  getProducts() {
    return JSON.stringify([
      { name: 'СТ', value: 'ST' },
      { name: 'СТА', value: 'STA' },
      { name: 'СТА 45', value: 'STA_45' },
      { name: 'СТ Эконом', value: 'ST_ECONOMY' },
      { name: 'СТ Лайт', value: 'ST_LITE' },
      { name: 'СТ 45', value: 'ST_45' },
      { name: 'СТ Бязь', value: 'ST_CALICO' },
      { name: 'БТ', value: 'BT' },
      { name: 'БТА', value: 'BTA' },
      { name: 'БТА 45', value: 'BTA_45' },
      { name: 'БТ Лайт', value: 'BT_LITE' },
      { name: 'БТ Эконом', value: 'BT_ECONOMY' },
      { name: 'БТ 45', value: 'BT_45' },
      { name: 'ЭВА', value: 'EVA' },
      { name: 'Эва ЛП', value: 'EVA_LP' },
      { name: 'ЭВА Эконом', value: 'EVA_ECONOMY' },
      { name: 'ЭВА Эконом 45', value: 'EVA_ECONOMY_45' },
      { name: 'Махра 150', value: 'MAHRA_150' },
      { name: 'Махра', value: 'MAHRA' },
      { name: 'Махра ЛП', value: 'MAHRA_LP' },
      { name: 'Махра А', value: 'MAHRA_A' },
      { name: 'Махра Эконом', value: 'MAHRA_ECONOMY' },
      { name: 'Махра 45', value: 'MAHRA_45' },
      { name: 'Махра Эконом 45', value: 'MAHRA_ECONOMY_45' },
      { name: 'Медиум', value: 'MEDIUM' },
      { name: 'Медиум 45', value: 'MEDIUM_45' },
      { name: 'Медиум ЛП', value: 'MEDIUM_LP' },
      { name: 'Медиум ЛП 45', value: 'MEDIUM_LP_45' },
      { name: 'Классик', value: 'CLASSIC' },
      { name: 'Классик 45', value: 'CLASSIC_45' },
      { name: 'Классик ЛП', value: 'CLASSIC_LP' },
      { name: 'Классик ЛП 45', value: 'CLASSIC_LP_45' },
      { name: 'Классик Плюс', value: 'CLASSIC_PLUS' },
      { name: 'Классик Плюс 45', value: 'CLASSIC_PLUS_45' },
      { name: 'Классик Плюс ЛП', value: 'CLASSIC_PLUS_LP' },
      { name: 'Классик Плюс ЛП 45', value: 'CLASSIC_PLUS_LP_45' },
      { name: 'Бизнес', value: 'BUISNESS' },
      { name: 'Бизнес 45', value: 'BUISNESS_45' },
      { name: 'Бизнес ЛП', value: 'BUISNESS_LP' },
      { name: 'Бизнес ЛП 45', value: 'BUISNESS_LP_45' },
      { name: 'Вьетнамки D3', value: 'VIETNAM_D3' },
      { name: 'Вьетнамки D4', value: 'VIETNAM_D4' },
      { name: 'Оптима', value: 'OPTIMA' },
      { name: 'Оптима 45', value: 'OPTIMA_45' },
      { name: 'Оптима А', value: 'OPTIMA_A' },
      { name: 'Оптима А 45', value: 'OPTIMA_A_45' },
    ]);
  }
}
